spring.application.name=backend
server.port=${PORT:8080}

# MongoDB Config
spring.data.mongodb.uri=${MONGO_URI:mongodb+srv://aananya_sh:Radha%4024@cluster0.wdtfldq.mongodb.net/engineering_super_app?appName=Cluster0}
spring.data.mongodb.auto-index-creation=true

# JWT Config
jwt.secret=${JWT_SECRET:engineering_super_app_jwt_secret_key_2024_very_secure_long_enough_for_hmac_sha256_key}
jwt.expiration=86400000

# File Upload Settings
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB
